# Generated by Django 2.2.6 on 2020-03-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipee_title', models.CharField(max_length=255)),
                ('recipee_image', models.ImageField(upload_to='images/')),
                ('recipee_body', models.TextField()),
                ('recipee_pubdate', models.DateTimeField()),
            ],
        ),
    ]
